language: python
cache:
  directories:
    - $HOME/.cache/igdiscover

python:
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda --add channels conda-forge
  - conda info -a
  - wget https://bitbucket.org/igdiscover/testdata/downloads/igdiscover-testdata-0.6.tar.gz
  - tar xvf igdiscover-testdata-0.6.tar.gz
  - "echo 'use_cache: true' > $HOME/.config/igdiscover.conf"

install:
  - conda env create -n testenv -f environment.lock.yml
  - conda install -n testenv pytest
  - source activate testenv
  - pip install .

script: tests/run.sh
