# abstract dependencies:
# python=3.6 sqt seaborn=0.7 snakemake cutadapt muscle pear flash igblast vsearch ruamel.yaml
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bcftools=1.6=0
- cutadapt=1.15=py36_0
- filechunkio=1.6=py36_0
- flash=1.2.11=0
- ftputil=3.2=py36_0
- htslib=1.7=0
- igblast=1.7.0=pl5.22.0_0
- muscle=3.8.1551=2
- pear=0.9.6=2
- pyasn1-modules=0.0.5=py36_0
- pysam=0.11.2.2=py36_1
- pysftp=0.2.9=py36_0
- rsa=3.1.4=py36_0
- ruamel.yaml=0.12.13=py36_0
- samtools=1.7=0
- snakemake=4.5.0=py36_0
- sqt=0.8.0=py36_0
- typing=3.5.2.2=py36_0
- urllib3=1.12=py36_0
- vsearch=2.6.0=0
- xopen=0.3.2=py36_0
- aioeasywebdav=2.2.0=py36_0
- aiohttp=2.0.7=py36_0
- appdirs=1.4.3=py_0
- asn1crypto=0.22.0=py36_0
- async-timeout=1.2.1=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- boto3=1.5.18=py_0
- botocore=1.8.32=py_0
- bzip2=1.0.6=1
- ca-certificates=2017.11.5=0
- cachetools=2.0.0=py36_0
- certifi=2017.11.5=py36_0
- cffi=1.11.2=py36_0
- chardet=3.0.4=py36_0
- configargparse=0.12.0=py36_0
- cryptography=2.1.4=py36_0
- curl=7.54.1=0
- cycler=0.10.0=py36_0
- dbus=1.10.22=0
- docutils=0.14=py36_0
- dropbox=7.3.1=py36_0
- expat=2.2.5=0
- fontconfig=2.12.1=6
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.53.5=0
- google-auth=1.2.1=py_0
- google-auth-httplib2=0.0.2=py36_0
- google-cloud-core=0.24.1=py36_0
- google-cloud-storage=1.1.1=py36_0
- google-resumable-media=0.0.2=py36_0
- googleapis-common-protos=1.5.3=py36_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- httplib2=0.10.3=py36_0
- icu=58.2=0
- idna=2.6=py36_1
- jmespath=0.9.3=py36_0
- jpeg=9b=2
- krb5=1.14.2=0
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.28=1
- libssh2=1.8.0=1
- libxcb=1.12=1
- libxml2=2.9.5=0
- matplotlib=2.1.1=py36_0
- multidict=2.1.4=py36_0
- ncurses=5.9=10
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- paramiko=2.3.1=py_0
- patsy=0.5.0=py36_0
- pcre=8.39=0
- perl=5.22.0.1=0
- pip=9.0.1=py36_1
- prettytable=0.7.2=py36_1
- protobuf=3.4.0=py36_0
- psutil=5.4.0=py36_0
- pyasn1=0.4.2=py_0
- pycparser=2.18=py36_0
- pynacl=1.1.2=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.3=0
- python-dateutil=2.6.1=py36_0
- python-irodsclient=0.7.0=py_0
- pytz=2017.3=py_2
- pyyaml=3.12=py36_1
- qt=5.6.2=3
- ratelimiter=1.2.0=py36_0
- readline=6.2=0
- requests=2.13.0=py36_0
- s3transfer=0.1.12=py36_0
- seaborn=0.7.1=py36_0
- setuptools=38.4.0=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- statsmodels=0.8.0=py36_0
- tk=8.5.19=2
- tornado=4.5.3=py36_0
- wheel=0.30.0=py36_2
- wrapt=1.10.11=py36_0
- xmlrunner=1.7.7=py_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- yaml=0.1.6=0
- yarl=0.10.0=py36_0
- zlib=1.2.8=3
- bcrypt=3.1.4=py36h621fe67_0
- intel-openmp=2018.0.0=hc7b2577_8
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- mkl=2018.0.1=h19d6760_4
- numpy=1.14.0=py36h3dfced4_1
- scipy=1.0.0=py36hbf646e7_0

